---
- name: prometheus | config | create
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: "{{ project.state }}"
    definition: "{{ lookup('template', '{{ item }}.yml.j2') }}"
  with_items:
  - secret
  - template
  tags:
  - prometheus
  - prometheus_secret