---
- name: prometheus | config | create
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: "{{ project.state }}"
    definition: "{{ lookup('template', '{{ item }}.yml.j2') }}"
  with_items:
  - secret
  - template
  tags:
  - prometheus
  - prometheus_config

- name: prometheus | config | customize
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: "{{ project.state }}"
    definition: "{{ lookup('template', 'customer/configmap-customize.yml.j2') }}"
  when: notificator.customize is defined
  tags:
  - prometheus
  - prometheus_config