---
- name: prometheus | exporter | deploy
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: "{{ project.state }}"
    definition: "{{ lookup('template', 'exporters/{{ item.exporter.name }}.yml.j2') }}"
  with_items: "{{ ScrapeMeta }}"
  when: item.exporter is defined and monitor[item.name] is defined 
  tags:
  - prometheus
  - prometheus_exporter