---
- name: prometheus | svc | exporter
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: "{{ project.state }}"
    definition: "{{ lookup('template', 'svc-exporter.yml.j2') }}"
  with_items: "{{ ScrapeMeta }}"
  when: item.exporter is defined and monitor[item.name] is defined
  tags:
  - prometheus
  - prometheus_svc
  - prometheus_svc_exporter

- name: prometheus | svc | component
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: "{{ project.state }}"
    definition: "{{ lookup('template', 'svc-component.yml.j2') }}"
  with_items:
  - {"name": "alertmanager", "port": 9093}
  - {"name": "prometheus", "port": 9090}
  tags:
  - prometheus
  - prometheus_svc
  - prometheus_svc_component

- name: prometheus | svc | prometheus | thanos
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: "{{ project.state }}"
    definition: "{{ lookup('template', 'svc-thanos.yml.j2') }}"
  when: component.prometheus.thanos.slb is defined and component.prometheus.thanos.slb == "enable"
  tags:
  - prometheus
  - prometheus_svc
  - prometheus_svc_component
